name: Scaffold Run

on:
  workflow_dispatch:
  # https://crontab.guru/
  schedule:
    - cron: "0 12 * * *"

jobs:
  agent:
    runs-on: ubuntu-latest
    env:
      GITSTAR_TOKEN: ${{ secrets.GITSTAR_TOKEN }}
      APPRISE_TELEGRAM: ${{ secrets.APPRISE_SERVER_TELEGRAM }}
    steps:
      - name: Checkout environment
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
      - name: Install requirements
        run: |
          pip install -r requirements.txt
      - name: Scaffold Run
        continue-on-error: true
        timeout-minutes: 10
        run: |
          cd example && python3 workflow.py